### ISSUE TITLE
小白社区贡献者-lvhongqiang的ICP流程认证

### ISSUE THREAD

**Issue by maohuaming** [sibbay-ai/icp-certification#2]
<mentor> 于 2018-04-03 对 <lvhongqiang> 进行 sibbay 贡献者认证。  

认证过程参考《贡献者认证流程》  
https://github.com/sibbay-ai/public/blob/master/%E8%B4%A1%E7%8C%AE%E8%80%85%E8%AE%A4%E8%AF%81%E6%B5%81%E7%A8%8B.md 

包含内容如下：  

### ICP 操作测试  

- [ ] 创建测试用 repo 并建立 master/develop 分支
- [ ] 将 mentor 添加为 Collaborator
- [ ] 创建 bug issue
- [ ] 创建需求 issue
- [ ] 提交 commit 并提交 pull request
- [ ] mentor 完成 review 与合并

### ICP 理解测试

- [ ] 创建提问用 issue
- [ ] 完成沟通

### 协作测试

- [ ] 创建协作 issue 并向 mentor 发起协作
- [ ] 完成协作过程并统计时间

**以上所有创建的 repo, issue, pr 需在此认证 issue 中进行引用回复到同一楼内。**

### 结果记录

认证结果由 <mentor> 以下面的表格进行记录，在认证过程完成后回复到此 issue 的末尾并上传至icp_auth_records目录。

| 项目  | 结果  |
|---|---|
| 申请者  | _github账号_ | 
| mentor  | _github账号_ | 
| icp流程测试 | _pr链接 及size数量_| 
| icp理解测试 | _issue链接_ |
| 协作测试 | _申请者耗时（小时）/协作者耗时（小时_ |
| issue响应速度 | _分钟/次_  |

**Comment by maohuaming** [comment]
@ben7th 认证issue已创建请处理。谢谢。

**Comment by ben7th** [comment]
@maohuaming 已标记

**Comment by maohuaming** [comment]
@ben7th 此issue请帮忙设置一下deadline，内容如下：
deadline：2018-04-10

**Comment by ben7th** [comment]
deadline：2018-04-10
