### ISSUE TITLE
小白社区贡献者——zhanhh的ICP流程认证测试

### ISSUE THREAD

**Issue by maohuaming** [sibbay-ai/icp-certification#9]
对小白社区贡献者——zhanhh 进行 sibbay ICP流程认证。

**Comment by maohuaming** [comment]
申请开发 deadline:2018-06-06 size:0.2 @ax003d

**Comment by maohuaming** [comment]
@ax003d 请指定assignee，打上ICP和size标签。

**Comment by maohuaming** [comment]
@ax003d 申请变更deadline，变更为：2018-06-08，变更原因：pr合并时间晚于issue的deadline时间。

**Comment by ax003d** [comment]
变更 deadline: 2018-06-08
